name: Elastic Builder
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sandbox.elastic.dev
        uses: actions/checkout@v2

      - name: Show workspace
        shell: bash
        run: ls -lat ${{ github.workspace }}

      - name: Deploy
        uses: elastic/builder@v21.3.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_MIGRATION_SANDBOX }} #Required
          vercel-project-name: migration-sandbox
          github-token: ${{ secrets.VERCEL_GITHUB_TOKEN }} #Optional
          vercel-args: --prod
          github-comment: false
