name: Builder PR Preview
on: [pull_request]

jobs:
  preview:
    name: Generate PR preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch into temp
        uses: actions/checkout@v3.0.1
        with:
          persist-credentials: false

      - name: Show workspace
        shell: bash
        run: ls -lat ${{ github.workspace }}

      - name: Generate preview
        id: vercel-deploy
        uses: elastic/builder@v21.3.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_MIGRATION_SANDBOX }} #Required
          vercel-project-name: migration-sandbox
          github-token: ${{ secrets.VERCEL_GITHUB_TOKEN }} #Optional
